language: minimal
sudo: required
services: 
  - docker

before_install:
  - docker build -t logeshkumar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run logeshkumar/react-test npm test -- --coverage

after_success:
  - docker build -t logeshkumar/multi-client ./client
  - docker build -t logeshkumar/multi-nginx ./nginx
  - docker build -t logeshkumar/multi-server ./server
  - docker build -t logeshkumar/multi-worker ./worker
  # login to dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push the images to dockerhub
  - docker push logeshkumar/multi-client
  - docker push logeshkumar/multi-nginx
  - docker push logeshkumar/multi-server
  - docker push logeshkumar/multi-worker